steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "--tag=gcr.io/$PROJECT_ID/cdxgen", "."]
  - name: "gcr.io/${PROJECT_ID}/cdxgen"
    args: ["-h"]

images: ["gcr.io/$PROJECT_ID/cdxgen"]
tags: ["cloud-builders-community"]
