steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "--tag=gcr.io/$PROJECT_ID/sast-scan", "."]
  - name: "gcr.io/${PROJECT_ID}/sast-scan"
    args: ["--help"]

images: ["gcr.io/$PROJECT_ID/sast-scan"]
tags: ["google-custom-builders"]
